### ISSUE TITLE
Reset Fixes/Changes (3):

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#90]
### Skyblock New Announcements

**>> Remember to fix the interval <<**
```
UltimateAnnounce:
  Chat:
    Prefix: &8(&a&l!&8)
    Header: &r
    Footer: &r
    space-between-messages: false
    Sound: NOTE_PLING
    Messages:
    - &7Create your island! &a&l/is&7!
    - &7Want to stay updated with the &c&llatest news&7?%n&8(&a&l!&8) &7Come and join us now at &a&l/forums&7!
    - &7Do you enjoy listening to &c&lmusic&7?%n&8(&a&l!&8) &7Be sure to join the &a&l/plugdj &7now&7!
    - &7Be sure to follow us on &d&lsocial media&7! &d&l/social
    - &7Did you know you get rewards for &c&lvoting&7?%n&8(&a&l!&8) &7Vote now using &a&l/vote&7!
    - &7Do you want to &d&lwin a rank&7?%n&8(&a&l!&8) &7Become a top voter now&7!
    - &7Bring &cdeath &7to your &c&lenemies&7! &a&l/warp pvp
    - &7Make sure you &a&lvote &7to claim your rewards&7! &a&l/vote
    - &7Hover over a players name to see their stats&7!
    - &7Be sure to keep updated with our rules&7! &a&l/rules
    - &7Did you know we have a &6&lcoinflip&7?%n&8(&a&l!&8) &7Check it out with &d&l/cf&7!
    - &7Did you know you could purchase &c&lcustom tags&7?%n&8(&a&l!&8) &7Check it out using &a&l/buy&7!
    - &7Feel free to ask a &a&lmember for staff &7for help when they are online&7!
    - &7Make sure you &a&lvote &7to claim your rewards&7! &a&l/vote
    - &7Need the TeamSpeak IP? &a&l/ts
    - &7Purchase items on the store &dfor your advantage&7! &a&l/buy
    Interval: 1
    Enabled: true
    Random: false
  Action:
    Messages:
    Interval: 0
    Duration: 600
    Enabled: true
    Random: false
  Title:
    Messages:
    - &7Demo Title message
    - &7Plugin created by Th3Tr0LLeR
    - &7Hello &a<player>&7! There are &a<online> &7players.
    - &7Your health: <health>
    - &7Your level: <level>
    Title: &7-=[&7Default Title&7]=-
    Interval: 50
    Enabled: false
    Random: false
```

### Skyblock add the alias's:

**/discord** should display the link https://discordapp.com/invite/uNRtac4
![discord](https://cloud.githubusercontent.com/assets/24858857/22864805/d40a5a66-f14f-11e6-9b18-c42873631f82.png)

**/ts** should display the link Ts.VenomPvP.org
![ts](https://cloud.githubusercontent.com/assets/24858857/22864813/ee199a7a-f14f-11e6-8adf-a23e9efba924.png)

Add **/plugdj** alias (link is on factions)

### Coinflip Layout

Current **./cf**:
![screenshot_16](https://cloud.githubusercontent.com/assets/24858857/22400212/c15f156e-e5a6-11e6-80b7-3c3f49768862.png)

Change the "Games Available" colour code to "**&b**".
You can also change the colour of the 6 glass panes.

Recommended: 
![screenshot_17](https://cloud.githubusercontent.com/assets/24858857/22400225/fa6da190-e5a6-11e6-8bde-53b7294cf5b9.png)

Just looks better.

### Factions Increase Combat Timer

Increase combat timer from 15 seconds to 20 seconds.

### SKYBLOCK: Crate Keys Lore

Change the lore of each crate key to:
![screenshot_22](https://cloud.githubusercontent.com/assets/24858857/22405176/55729124-e636-11e6-9948-327443d6798c.png)
![screenshot_23](https://cloud.githubusercontent.com/assets/24858857/22405177/570fb08e-e636-11e6-8d19-e52704a0a802.png)
![screenshot_24](https://cloud.githubusercontent.com/assets/24858857/22405178/586b69d2-e636-11e6-9f53-dc8533e1b826.png)

Just looks better.

### SKYBLOCK: Vote Messages

Currently just spams with:
![screenshot_25](https://cloud.githubusercontent.com/assets/24858857/22405221/39708818-e637-11e6-8a9d-338a802d28a7.png)

Change it to something like: 
![screenshot_27](https://cloud.githubusercontent.com/assets/24858857/22405306/ab8351e6-e638-11e6-9605-9dcb068e5dd7.png)
or....
![screenshot_28](https://cloud.githubusercontent.com/assets/24858857/22405334/fc61969a-e638-11e6-9b42-99bab0362dab.png)

Just copy over from factions

### Skyblock Clear Lagg Messages 

Change to one on factions.
